# Generated by Django 6.0.2 on 2026-02-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active - In Use'), ('Maintenance', 'Needs Maintenance'), ('Retired', 'Retired/Out of Service')], default='Active', max_length=20)),
                ('last_inspected', models.DateField(auto_now=True)),
            ],
        ),
    ]
